"""create external user table and add relation for business and external user

Revision ID: 821807029184
Revises: 
Create Date: 2023-05-08 01:03:43.396558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821807029184'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_external_users_id'), 'external_users', ['id'], unique=False)
    op.create_index(op.f('ix_external_users_phone_no'), 'external_users', ['phone_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_users_phone_no'), table_name='external_users')
    op.drop_index(op.f('ix_external_users_id'), table_name='external_users')
    op.drop_table('external_users')
    # ### end Alembic commands ###
